services:
  db:
    image: mysql:8.4
    container_name: db-banco-imobiliario
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: bancoimobiliario
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - network-banco-imobiliario

  localstack:
    image: localstack/localstack
    container_name: localstack
    restart: always
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3,sqs,sns
      DEFAULT_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - network-banco-imobiliario

networks:
  network-banco-imobiliario:

volumes:
  db_data:
